InvalidCustomInterval = "The 'CustomInterval' field must be an integer > 0."
InvalidJsonFormat = "Invalid Json Format, input data is Empty."
RequiredSeries = "The 'Series' field is required in request."
RequiredGranularity = "The 'Granularity' field is required in request."
InvalidGranularity = "The 'Granularity' field can only be one of the following: {0}."
InvalidPeriod = "The 'Period' field must be an integer >= 0."
InvalidFillUpMode = "The 'fillUpMode' field can only be one of the following: {0}."
InvalidFixedValue = "The 'fixedValue' field must be a number."
InsufficientPoints = "The 'Series' field must have more than 2 periods points"
InvalidAlpha = "The 'Alpha' field must > 0."
InvalidAnomalyRatio = "The 'MaxAnomalyRatio' field must be less than 50% of the series points (0 < " \
                      "MaxAnomalyRatio < 0.5)."
InvalidSensitivity = "The 'Sensitivity' field must be an integer between 0 and 99."
InvalidSeries = "The 'Series' field cannot be empty."
InvalidSeriesValue = "The 'Series' field cannot have none values."
InvalidSeriesType = "The 'Series' field must be array/list type."
NotEnoughPoints = "The 'Series' field must have at least 12 points."
TooManyPoints = "The 'Series' field cannot have more than 8640 points."
InvalidSeriesFormat = "'Timestamp' or 'Value' is malformed in 'Series' Field."
InvalidSeriesOrder = "The 'Series' field must be sorted by timestamp in ascending order."
DuplicateSeriesTimestamp = "The 'Series' field cannot have duplicated timestamp."
InvalidSeriesTimestamp = "The 'Timestamp' at index {0} is invalid in {1} granularity with {2} gran as interval."
InvalidThreshold = "The 'Threshold' field must be a float."
