[tool.poetry]
name = "anomaly-detector"
version = "0.1.0"
description = ""
authors = ["juaduan <juanyong.duan@microsoft.com>"]
readme = "README.md"
packages = [{include = "anomaly_detector"}]

[tool.poetry.dependencies]
python = "^3.11"
mlflow = "^2.9.2"
torch = "^2.1.2"
tqdm = "^4.66.1"
pybind11 = "^2.11.1"
pytest = "^7.4.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
